### ISSUE TITLE
[20:15:07 WARN]: java.lang.NoSuchFieldException: meta

### ISSUE THREAD

**Issue by hed516** [m1919810/LogiTech#1]
[20:15:07 INFO]: [LOGITECH] 自定义物品加载完毕
[20:15:07 INFO]: [LOGITECH] 物品模板加载完毕
[20:15:07 INFO]: [LOGITECH] INVOKE STACK FAILED,PLEASE CHECK LOGGER!!!!!!
[20:15:07 WARN]: java.lang.NoSuchFieldException: meta
[20:15:07 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2782)
[20:15:07 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90)
[20:15:07 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source)
[20:15:07 WARN]:        at S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar//me.matl114.logitech.Utils.CraftUtils.<clinit>(CraftUtils.java:96)
[20:15:07 WARN]:        at S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar//me.matl114.logitech.SlimefunItem.Machines.AbstractMachine.<init>(AbstractMachine.java:170)
[20:15:07 WARN]:        at S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar//me.matl114.logitech.SlimefunItem.Machines.AbstractProcessor.<init>(AbstractProcessor.java:44)
[20:15:07 WARN]:        at S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar//me.matl114.logitech.SlimefunItem.Machines.AbstractProcessor.<init>(AbstractProcessor.java:68)
[20:15:07 WARN]:        at S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar//me.matl114.logitech.SlimefunItem.Machines.SpecialMachines.BoolGenerator.<init>(BoolGenerator.java:42)
[20:15:07 WARN]:        at S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar//me.matl114.logitech.SlimefunItem.AddSlimefunItems.<clinit>(AddSlimefunItems.java:428)
[20:15:07 WARN]:        at S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar//me.matl114.logitech.MyAddon.onEnable(MyAddon.java:81)
[20:15:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[20:15:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[20:15:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[20:15:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[20:15:07 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[20:15:07 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[20:15:07 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
[20:15:07 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
[20:15:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[20:15:07 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[20:15:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[20:15:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:15:07 INFO]: [LOGITECH] DISABLING RELEVENT FEATURE
[20:15:08 ERROR]: Error occurred while enabling LogiTech vBuild 11 (git 73d5a2b) (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar/me.matl114.logitech.MyAddon.onEnable(MyAddon.java:81) ~[S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack to org.bukkit.craftbukkit.inventory.CraftItemStack
        at java.base/java.lang.Class.cast(Class.java:4067) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.getCraftStack(CraftItemStack.java:46) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.equals(CraftItemStack.java:64) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.inventory.ItemStack.equals(ItemStack.java:326) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Slimefun-dc72b4b-Beta.jar/io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack.equals(SlimefunItemStack.java:336) ~[Slimefun-dc72b4b-Beta.jar:?]
        at org.bukkit.inventory.ItemStack.equals(ItemStack.java:326) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.util.HashMap.putVal(HashMap.java:641) ~[?:?]
        at java.base/java.util.HashMap.put(HashMap.java:618) ~[?:?]
        at S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar/me.matl114.logitech.Utils.AddUtils.randItemStackFactory(AddUtils.java:635) ~[S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar:?]
        at S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar/me.matl114.logitech.SlimefunItem.AddSlimefunItems.<clinit>(AddSlimefunItems.java:1227) ~[S_[逻辑工艺]LogiTech-Build 11 (git 73d5a2b).jar:?]
        ... 13 more

**Comment by m1919810** [comment]
暂时不会支持1.21.1,直到粘液本体稳定兼容

**Comment by m1919810** [comment]
已经修复并且增加了1.21兼容
