### ISSUE TITLE
不兼容1.21

### ISSUE THREAD

**Issue by CuteLittleSky** [m1919810/LogiTech#2]
问题类似https://github.com/ytdd9527/NetworksExpansion/issues/28
点击物品后报错如下: 已测试1.20无问题 (还有请问快捷机器和原版有什么不同吗?加了之后可以删掉原版的吗)
[17:25:15 ERROR]: [Slimefun] An exception thrown while handling the click: 
java.lang.NoClassDefFoundError: me/matl114/logitech/SlimefunItem/Machines/RecipeDisplay$1
        at LogiTech-Build 20 (git 322e311).jar/me.matl114.logitech.SlimefunItem.Machines.RecipeDisplay.addRecipeInfo(RecipeDisplay.java:23) ~[LogiTech-Build 20 (git 322e311).jar:?]
        at LogiTech-Build 20 (git 322e311).jar/me.matl114.logitech.SlimefunItem.Machines.RecipeDisplay._getDisplayRecipes(RecipeDisplay.java:111) ~[LogiTech-Build 20 (git 322e311).jar:?]
        at LogiTech-Build 20 (git 322e311).jar/me.matl114.logitech.SlimefunItem.Machines.AbstractTransformer._getDisplayRecipes(AbstractTransformer.java:73) ~[LogiTech-Build 20 (git 322e311).jar:?]
        at LogiTech-Build 20 (git 322e311).jar/me.matl114.logitech.SlimefunItem.CustomSlimefunItem.getDisplayRecipes(CustomSlimefunItem.java:48) ~[LogiTech-Build 20 (git 322e311).jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.displayRecipes(SurvivalSlimefunGuide.java:753) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.displayItem(SurvivalSlimefunGuide.java:609) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.core.guide.GuideHistory.open(GuideHistory.java:190) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.core.guide.GuideHistory.goBack(GuideHistory.java:181) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.lambda$addBackButton$18(SurvivalSlimefunGuide.java:709) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:59) ~[Slimefun-fdb765c-Insider.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor220.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2291-bba87bf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3271) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at java.base/java.lang.Thread.run(Thread.java:1584) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.matl114.logitech.SlimefunItem.Machines.RecipeDisplay$1
        ... 35 more
[17:25:16 ERROR]: Could not pass event PlayerRightClickEvent to Slimefun vfdb765c-Insider
java.lang.NoClassDefFoundError: me/matl114/logitech/SlimefunItem/Machines/RecipeDisplay$1
        at LogiTech-Build 20 (git 322e311).jar/me.matl114.logitech.SlimefunItem.Machines.RecipeDisplay.addRecipeInfo(RecipeDisplay.java:23) ~[LogiTech-Build 20 (git 322e311).jar:?]
        at LogiTech-Build 20 (git 322e311).jar/me.matl114.logitech.SlimefunItem.Machines.RecipeDisplay._getDisplayRecipes(RecipeDisplay.java:111) ~[LogiTech-Build 20 (git 322e311).jar:?]
        at LogiTech-Build 20 (git 322e311).jar/me.matl114.logitech.SlimefunItem.Machines.AbstractTransformer._getDisplayRecipes(AbstractTransformer.java:73) ~[LogiTech-Build 20 (git 322e311).jar:?]
        at LogiTech-Build 20 (git 322e311).jar/me.matl114.logitech.SlimefunItem.CustomSlimefunItem.getDisplayRecipes(CustomSlimefunItem.java:48) ~[LogiTech-Build 20 (git 322e311).jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.displayRecipes(SurvivalSlimefunGuide.java:753) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.displayItem(SurvivalSlimefunGuide.java:609) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.core.guide.GuideHistory.open(GuideHistory.java:190) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.core.guide.GuideHistory.openLastEntry(GuideHistory.java:166) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.core.guide.SlimefunGuide.openGuide(SlimefunGuide.java:63) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunGuideListener.openGuide(SlimefunGuideListener.java:78) ~[Slimefun-fdb765c-Insider.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunGuideListener.onInteract(SlimefunGuideListener.java:52) ~[Slimefun-fdb765c-Insider.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor316.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2291-bba87bf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Slimefun-fdb765c-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.onRightClick(SlimefunItemInteractListener.java:69) ~[Slimefun-fdb765c-Insider.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor225.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2291-bba87bf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:602) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:558) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:553) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2084) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
        at java.base/java.lang.Thread.run(Thread.java:1584) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.matl114.logitech.SlimefunItem.Machines.RecipeDisplay$1
        ... 48 more

**Comment by m1919810** [comment]
暂时不支持1.21的沟槽更新
原版快捷机器是什么
反正比fastmachine好就对了

**Comment by balugaq** [comment]
应该不会触发 NoClassDefFound 才对，可能在这之前应该就已经有报错了

**Comment by m1919810** [comment]
已经添加1.21的兼容

**Comment by m1919810** [comment]
已经添加1.21兼容
